# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main(test).ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(868, 675)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Time = QtWidgets.QLCDNumber(self.centralwidget)
        self.Time.setGeometry(QtCore.QRect(450, 0, 221, 81))
        self.Time.setObjectName("Time")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(10, 100, 274, 450))
        self.groupBox.setStatusTip("")
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.registr = QtWidgets.QPushButton(self.groupBox)
        self.registr.setCheckable(False)
        self.registr.setAutoExclusive(False)
        self.registr.setDefault(False)
        self.registr.setFlat(False)
        self.registr.setObjectName("registr")
        self.gridLayout.addWidget(self.registr, 2, 1, 1, 1)
        self.scan = QtWidgets.QPushButton(self.groupBox)
        self.scan.setObjectName("scan")
        self.gridLayout.addWidget(self.scan, 2, 0, 1, 1)
        self.Team2_listWidget = QtWidgets.QListWidget(self.groupBox)
        self.Team2_listWidget.setObjectName("Team2_listWidget")
        self.gridLayout.addWidget(self.Team2_listWidget, 1, 0, 1, 2)
        self.Team1_listWidget = QtWidgets.QListWidget(self.groupBox)
        self.Team1_listWidget.setObjectName("Team1_listWidget")
        self.gridLayout.addWidget(self.Team1_listWidget, 0, 0, 1, 2)
        self.players_init = QtWidgets.QPushButton(self.groupBox)
        self.players_init.setObjectName("players_init")
        self.gridLayout.addWidget(self.players_init, 3, 0, 1, 2)
        self.team1_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.team1_lineEdit.setGeometry(QtCore.QRect(330, 120, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.team1_lineEdit.setFont(font)
        self.team1_lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.team1_lineEdit.setAutoFillBackground(True)
        self.team1_lineEdit.setText("")
        self.team1_lineEdit.setReadOnly(True)
        self.team1_lineEdit.setObjectName("team1_lineEdit")
        self.team2_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.team2_lineEdit.setGeometry(QtCore.QRect(640, 120, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.team2_lineEdit.setFont(font)
        self.team2_lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.team2_lineEdit.setAutoFillBackground(True)
        self.team2_lineEdit.setReadOnly(True)
        self.team2_lineEdit.setClearButtonEnabled(False)
        self.team2_lineEdit.setObjectName("team2_lineEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 180, 153, 157))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.t1_pl1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.t1_pl1.setReadOnly(True)
        self.t1_pl1.setObjectName("t1_pl1")
        self.gridLayout_2.addWidget(self.t1_pl1, 0, 0, 1, 1)
        self.t1_pl2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.t1_pl2.setReadOnly(True)
        self.t1_pl2.setObjectName("t1_pl2")
        self.gridLayout_2.addWidget(self.t1_pl2, 1, 0, 1, 1)
        self.t1_pl3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.t1_pl3.setReadOnly(True)
        self.t1_pl3.setObjectName("t1_pl3")
        self.gridLayout_2.addWidget(self.t1_pl3, 2, 0, 1, 1)
        self.t1_pl4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.t1_pl4.setReadOnly(True)
        self.t1_pl4.setObjectName("t1_pl4")
        self.gridLayout_2.addWidget(self.t1_pl4, 3, 0, 1, 1)
        self.t1_pl5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.t1_pl5.setReadOnly(True)
        self.t1_pl5.setObjectName("t1_pl5")
        self.gridLayout_2.addWidget(self.t1_pl5, 4, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(640, 180, 153, 157))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.t2_pl1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.t2_pl1.setReadOnly(True)
        self.t2_pl1.setObjectName("t2_pl1")
        self.gridLayout_3.addWidget(self.t2_pl1, 0, 0, 1, 1)
        self.t2_pl2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.t2_pl2.setReadOnly(True)
        self.t2_pl2.setObjectName("t2_pl2")
        self.gridLayout_3.addWidget(self.t2_pl2, 1, 0, 1, 1)
        self.t2_pl3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.t2_pl3.setReadOnly(True)
        self.t2_pl3.setObjectName("t2_pl3")
        self.gridLayout_3.addWidget(self.t2_pl3, 2, 0, 1, 1)
        self.t2_pl4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.t2_pl4.setReadOnly(True)
        self.t2_pl4.setObjectName("t2_pl4")
        self.gridLayout_3.addWidget(self.t2_pl4, 3, 0, 1, 1)
        self.t2_pl5 = QtWidgets.QLineEdit(self.groupBox_3)
        self.t2_pl5.setReadOnly(True)
        self.t2_pl5.setObjectName("t2_pl5")
        self.gridLayout_3.addWidget(self.t2_pl5, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(530, 110, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.net_worth = QtWidgets.QLabel(self.centralwidget)
        self.net_worth.setGeometry(QtCore.QRect(510, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.net_worth.setFont(font)
        self.net_worth.setObjectName("net_worth")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 868, 21))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBase_Health = QtWidgets.QAction(MainWindow)
        self.actionBase_Health.setObjectName("actionBase_Health")
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionBase_Health)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Выбор команд:"))
        self.registr.setText(_translate("MainWindow", "Зарегистрировать"))
        self.scan.setText(_translate("MainWindow", "Сканировать"))
        self.players_init.setText(_translate("MainWindow", "Инициализировать игроков"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Игроки:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Игроки:"))
        self.label.setText(_translate("MainWindow", "Net Worth"))
        self.net_worth.setText(_translate("MainWindow", "TextLabel"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionBase_Health.setText(_translate("MainWindow", "Base Health"))

