# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main(test).ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(868, 675)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Time = QtWidgets.QLCDNumber(self.centralwidget)
        self.Time.setGeometry(QtCore.QRect(340, 0, 221, 81))
        self.Time.setObjectName("Time")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(10, 100, 274, 450))
        self.groupBox.setStatusTip("")
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.Team1_listWidget = QtWidgets.QListWidget(self.groupBox)
        self.Team1_listWidget.setObjectName("Team1_listWidget")
        self.gridLayout.addWidget(self.Team1_listWidget, 0, 0, 1, 2)
        self.Team2_listWidget = QtWidgets.QListWidget(self.groupBox)
        self.Team2_listWidget.setObjectName("Team2_listWidget")
        self.gridLayout.addWidget(self.Team2_listWidget, 1, 0, 1, 2)
        self.scan = QtWidgets.QPushButton(self.groupBox)
        self.scan.setObjectName("scan")
        self.gridLayout.addWidget(self.scan, 2, 0, 1, 1)
        self.registr = QtWidgets.QPushButton(self.groupBox)
        self.registr.setCheckable(False)
        self.registr.setAutoExclusive(False)
        self.registr.setDefault(False)
        self.registr.setFlat(False)
        self.registr.setObjectName("registr")
        self.gridLayout.addWidget(self.registr, 2, 1, 1, 1)
        self.team1_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.team1_lineEdit.setGeometry(QtCore.QRect(330, 120, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.team1_lineEdit.setFont(font)
        self.team1_lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.team1_lineEdit.setAutoFillBackground(True)
        self.team1_lineEdit.setText("")
        self.team1_lineEdit.setReadOnly(True)
        self.team1_lineEdit.setObjectName("team1_lineEdit")
        self.team2_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.team2_lineEdit.setGeometry(QtCore.QRect(640, 120, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.team2_lineEdit.setFont(font)
        self.team2_lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.team2_lineEdit.setAutoFillBackground(True)
        self.team2_lineEdit.setReadOnly(True)
        self.team2_lineEdit.setClearButtonEnabled(False)
        self.team2_lineEdit.setObjectName("team2_lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 868, 21))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBase_Health = QtWidgets.QAction(MainWindow)
        self.actionBase_Health.setObjectName("actionBase_Health")
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionBase_Health)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Выбор команд:"))
        self.scan.setText(_translate("MainWindow", "Сканировать"))
        self.registr.setText(_translate("MainWindow", "Зарегистрировать"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionBase_Health.setText(_translate("MainWindow", "Base Health"))

